version: '3'
services:
   db:
      image: postgres
      container_name: db
      restart: always
      ports:
         - 2345:5432
      env_file:
         - .env.development
      volumes:
         - pg:/var/lib/postgresql/data
   node_app:
      container_name: node_app
      build: .
      ports:
         - 5000:5000
      env_file:
         - .env.development
      depends_on:
         - db
      volumes:
         - .:/usr/src
         - /usr/src/node_modules

volumes:
   pg:
